version: '3.8'

services:
  backend:
    build:
      context: ./back_end
      dockerfile: Dockerfile
    container_name: petstore-backend
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=PetStoreDB;User Id=sa;Password=YourStrongPassword123!
    depends_on:
      - db
    networks:
      - petstore_network

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    container_name: petstore-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
      - NEXT_PUBLIC_AI_URL=http://ai:8000
    depends_on:
      - backend
      - ai
    networks:
      - petstore_network

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: petstore-ai
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here
    networks:
      - petstore_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petstore-db
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - petstore_network

networks:
  petstore_network:
    driver: bridge
